FORMAT: 1A
HOST: https://api.wesport.it

# WeSport API

##UTENTE 
### profilo utente
####info profilo UR [GET /api/profile]
+ Request (application/json)
    + Headers

            Authorization: `Bearer {token}`

+ Response 200 (application/json)
    + Attributes (object)
        + nomeutente: `lucaverdi03` (string) - nome utente
        + email: `lucaverdi03@gmail.com` (string) - email utente
        + tipo: `registrato` (string) tipologia di utente
        + punti: `20` (number) - unti totali accumulati
        + fotoprofilo: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhGqmwotiLoQeHHhOG8tiIOUs-gJOKXL98pw&s` (string) - URL della foto del profilo
        + selfdescription: `amante della natura e della bici` (string) - selfdescription
        + segnalazioni: `` (array) - segnalazioni
        + annunci: `` (array) - annunci
        
+ Response 401 (application/json)
    + Attributes (object)
        + message: "utente non autorizato" (string)


###gestione regsitrazione

###login con google [GET /auth/google]
+ Request
    + Headers
    
          Authorization: `Bearer {token}`

+ Response 302 (text/plain)
    + Headers
    
            Location: https://accounts.google.com/o/oauth2/auth

###login [POST /login]
+ Request (application/json)

    + Attributes (object)
        + email: `lucaverdi03@gmail.com` (string, required) - Email dell'utente
        + password: `password123` (string, required) - Password dell'utente

+ Response 200 (application/json)

    + Attributes (object)
        + success: true (boolean)
        + message: "login riuscito" (string)
        + token: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c` (string)

+ Response 401 (application/json)

    + Attributes (object)
        + message: "credenziali non valide" (string)

###logout [GET /logout]
+ Request
    + Headers
    
            Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c`

+ Response 200 (text/plain)
    + Body
    
            "logout effettuato con successo"

+ Response 401 (text/plain)
    + Body
    
            "utente non autorizzato"
            

###eliminazione utente [DELETE /delete]
+ Parameters
    + formId: `67890` (string) - The unique identifier of the form to delete

+ Request
    + Headers
    
            Authorization: `Bearer {admin_token}`
            
+ Response 204 (application/json)
    + Attributes (object)
        + message: "utente eliminato con successo" (string)

+ Response 401 (application/json)
    + Attributes (object)
        + message: "non autenticato" (string)
  
+ Response 403 (application/json)
    + Attributes (object) 
        + message: "accesso negato" (string) 

+ Response 404 (text/plain)
    + Attributes (object)
        + message:  "utente non trovato" (string)


##ANNUNCI 
###lista annunci
###chat annunci
###creazione nuovo annuncio

##AVVISI
###lista avvisi
###nuovo avviso

##AMMINISTRATORE
###lato comune

##PERCORSI
###lista percorsi
###mappe
###nuovo percorso

##GESTIONE AUTENTICAZIONE

##AZIENDA VERIFICATA
###profilo azienda verificata [POST ]


##SEGNALAZIONI
###segnalazione

###lista segnalazioni
###compilazione modulo segnalazioni