openapi: 3.0.3
info:
  title: API WeSport
  version: 1.0.0

servers:
  - url: https://api.weSport.it/v1

#------------------------------------------------------

paths:
  /annunci:
    $ref: './paths/annunci.yaml'
  /areesportive:
    $ref: './paths/areesportive.yaml'
  /areesportive/searchAS:
    $ref: './paths/areesportive/searchAS.yaml'
  /aziende:
    $ref: './paths/aziende.yaml'
  /chats:
    $ref: './paths/chats.yaml'
  /messaggi:
    $ref: './paths/messaggi.yaml'
  /percorsi:
    $ref: './paths/percorsi.yaml'
  /sports:
    $ref: './paths/sports.yaml'
  /utentiregistrati:
    $ref: './paths/utentiregistrati.yaml'
  /utenti:
    $ref: './paths/utenti.yaml'
  /segnalazioni:
    $ref: './paths/segnalazioni.yaml'
  /avvisi:
    $ref: './paths/avvisi.yaml'
  /auth/login:
    $ref: './paths/auth.yaml/auth/login'
  /auth/logout:
    $ref: './paths/auth.yaml/auth/logout'
  /profileUtente:
    $ref: './paths/utentiregistrati.yaml/profiloUtente'

#------------------------------------------------------------

components:
  schemas:
    annuncio:
      $ref: './components/schemas/annuncio.yaml'
    areasportiva:
      $ref: './components/schemas/areasportiva.yaml'
    azienda:
      $ref: './components/schemas/azienda.yaml'
    chat:
      $ref: './components/schemas/chat.yaml'
    messaggio:
      $ref: './components/schemas/messaggio.yaml'
    percorso:
      $ref: './components/schemas/percorso.yaml'
    sport:
      $ref: './components/schemas/sport.yaml'
    utenteregistrato:
      $ref: './components/schemas/utenteregistrato.yaml'
    utente:
      $ref: './components/schemas/utente.yaml'
    segnalazione:
      $ref: './components/schemas/segnalazione.yaml'
    avviso:
      $ref: './components/schemas/avviso.yaml'
    LoginRequest:
      $ref: './components/schemas/Login/LoginRequest.yaml'
    AuthToken:
      $ref: './components/schemas/Login/AuthToken.yaml'